Add support for auto switch IME between normal mode and insert mode
qvacua/vimr pull request #900
Opened 2022-02-06 07:47 UTC by georgealbert

This allows VimR to switch IME from a non-ascii input source to  the ascii one when in normal mode, and swich to last input source used in insert mode when enters insert mode.

2022-03-05 09:51 UTC, qvacua commented
Thank you! This has bothered me few times, too, but did not have the chance to find out how to handle input sources. Sorry, it took so long; I've commented few minor things.

2022-03-05 19:24 UTC, qvacua requested changes
I've commented two minor things.

2022-03-07 03:27 UTC, georgealbert commented on NvimView/Sources/NvimView/NvimView.swift
> +  var lastMode = ""
I know little of swift. I dont' know how to use CursorModeShape, I use a String for lastMode. We can use CursorModeShape for lastMode

2022-03-07 03:28 UTC, georgealbert commented on NvimView/Sources/NvimView/NvimView.swift
> +  var asciiImSource : TISInputSource?
We can initialize both TISInputSource to nil.

2022-03-07 20:22 UTC, qvacua commented on NvimView/Sources/NvimView/NvimView.swift
> +  var lastMode = ""
OK, I'll merge the PR and then slightly refactor. Then, you can comment and/or suggest improvements 😀

2022-03-07 20:22 UTC, merged